services:

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: lbaw2353
      POSTGRES_PASSWORD: lROapSCU
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@lbaw.com
      PGADMIN_DEFAULT_PASSWORD: pg!password
    ports:
      - "4321:80"
    depends_on:
      - postgres
